2020-03-29 01:26:57,641 ERROR: Exception on /alive [GET] [in d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PROGRAMMING\github\firestone_api\app\auth\license.py", line 24, in decorator
    response = json.loads(response.text)
  File "C:\Program Files\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-03-29 01:26:57,683 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:48]
2020-03-29 01:26:57,683 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:48]
2020-03-29 01:26:57,683 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:48]
2020-03-29 01:26:57,683 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:48]
2020-03-29 01:26:57,683 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:48]
2020-03-29 01:26:57,683 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:48]
2020-03-29 01:26:58,043 ERROR: Exception on /map [GET] [in d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PROGRAMMING\github\firestone_api\app\auth\license.py", line 24, in decorator
    response = json.loads(response.text)
  File "C:\Program Files\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-03-29 01:26:58,043 ERROR: Exception on /map [GET] [in d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PROGRAMMING\github\firestone_api\app\auth\license.py", line 24, in decorator
    response = json.loads(response.text)
  File "C:\Program Files\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-03-29 01:26:58,043 ERROR: Exception on /map [GET] [in d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PROGRAMMING\github\firestone_api\app\auth\license.py", line 24, in decorator
    response = json.loads(response.text)
  File "C:\Program Files\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-03-29 01:26:58,043 ERROR: Exception on /map [GET] [in d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PROGRAMMING\github\firestone_api\app\auth\license.py", line 24, in decorator
    response = json.loads(response.text)
  File "C:\Program Files\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-03-29 01:26:58,075 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:48]
2020-03-29 01:26:58,075 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:48]
2020-03-29 01:26:58,075 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:48]
2020-03-29 01:26:58,075 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:48]
2020-03-29 01:26:58,075 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:48]
2020-03-29 01:26:58,075 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:48]
2020-03-29 01:26:58,075 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:48]
